package gr.aueb.cf.teachersjaxapp.dao;


import gr.aueb.cf.teachersjaxapp.dao.exceptions.TeacherDAOException;
import gr.aueb.cf.teachersjaxapp.model.Teacher;
import gr.aueb.cf.teachersjaxapp.service.util.DBUtil;

import javax.ws.rs.ext.Provider;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

@Provider
public class TeacherDAOImpl implements ITeacherDAO {

    @Override
    public Teacher insert(Teacher teacher) throws TeacherDAOException {
        String sql = "INSERT INTO TEACHERS (FIRSTNAME, LASTNAME) VALUES (?, ?)";
        int autoGeneratedId = 0;

        try (Connection conn = DBUtil.getConnection();
             PreparedStatement p = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            String firstname = teacher.getFirstname();
            String lastname = teacher.getLastname();

            p.setString(1, firstname);
            p.setString(2, lastname);
            p.executeUpdate();

            ResultSet generatedKeys = p.getGeneratedKeys();
            if (generatedKeys.next()){
                autoGeneratedId = generatedKeys.getInt(1);
            }

            Teacher insertedTeacher = new Teacher();
            insertedTeacher.setId(autoGeneratedId);
            insertedTeacher.setFirstname(teacher.getFirstname());
            insertedTeacher.setLastname(teacher.getLastname());

            return insertedTeacher;
        } catch (SQLException | ClassNotFoundException e) {
            // e.printStackTrace(); // logging
            throw new TeacherDAOException("SQL Error in Teacher " + teacher + " insertion");
        }
    }

    @Override
    public Teacher update(Teacher teacher) throws TeacherDAOException {
        String sql = "UPDATE TEACHERS SET FIRSTNAME = ?, LASTNAME = ? WHERE ID = ?";

        try (Connection conn = DBUtil.getConnection();
             PreparedStatement p = conn.prepareStatement(sql)) {

            int id = teacher.getId();
            String firstname = teacher.getFirstname();
            String lastname = teacher.getLastname();

            p.setString(1, firstname);
            p.setString(2, lastname);
            p.setInt(3, id);
            p.executeUpdate();
            return teacher;
        } catch (SQLException | ClassNotFoundException e) {
            //e.printStackTrace();
            throw new TeacherDAOException("SQL Error in Teacher " + teacher.getLastname()
                    + " update");
        }
    }

    @Override
    public void delete(int id) throws TeacherDAOException {
        String sql = "DELETE FROM TEACHERS WHERE ID = ?";

        try (Connection conn = DBUtil.getConnection();
             PreparedStatement p = conn.prepareStatement(sql)) {
            p.setInt(1, id);
            p.executeUpdate();
        } catch (SQLException | ClassNotFoundException e) {
            //e.printStackTrace();
            throw new TeacherDAOException("SQL Error in Teacher with id = "
                    + id  + " deleted");
        }
    }

    @Override
    public List<Teacher> getByLastname(String lastname) throws TeacherDAOException {
        System.out.println("DAO " + lastname);
        String sql = "SELECT ID, FIRSTNAME, LASTNAME FROM TEACHERS WHERE LASTNAME LIKE ?";
        ResultSet rs;
        List<Teacher> teachers = new ArrayList<>();

        try (Connection conn = DBUtil.getConnection();
             PreparedStatement p = conn.prepareStatement(sql)) {

            p.setString(1, lastname + '%');
            rs = p.executeQuery();

            while (rs.next()) {
                Teacher teacher = new Teacher(rs.getInt("ID"),rs.getString("FIRSTNAME"), rs.getString("LASTNAME"));
                teachers.add(teacher);
            }
            return teachers;
        } catch (SQLException | ClassNotFoundException e) {
            // e.printStackTrace();
            throw new TeacherDAOException("SQL Error in Teacher with lastname = " + lastname);
        }
    }

    @Override
    public Teacher getById(int id) throws TeacherDAOException {
        Teacher teacher = null;
        ResultSet rs;
        String sql = "SELECT ID, FIRSTNAME, LASTNAME FROM TEACHERS WHERE ID = ?";

        try (Connection conn = DBUtil.getConnection();
             PreparedStatement p = conn.prepareStatement(sql)) {

            p.setInt(1, id);
            rs = p.executeQuery();

            if (rs.next()) {
                teacher = new Teacher(rs.getInt("ID"), rs.getString("FIRSTNAME"),rs.getString("LASTNAME"));
            }
            return teacher;
        } catch (SQLException | ClassNotFoundException e) {
            // e.printStackTrace();
            throw new TeacherDAOException("SQL Error in Teacher with id = " + id);
        }
    }
}
